### ISSUE TITLE
Run will Exit status 1

### ISSUE THREAD

**Issue by heyv5** [oligot/go-mod-upgrade#10]
![image](https://user-images.githubusercontent.com/17784076/111062338-349bcb00-84e3-11eb-8d3d-d6428b16476c.png)

I run it failed with exit status 1

**Comment by oligot** [comment]
Hi,

Can you share your go.mod file ?
What's your go version ?
Are you using the latest go-mod-upgrade version (v0.4.1) ?

**Comment by heyv5** [comment]
> Hi,
> 
> Can you share your go.mod file ?
> What's your go version ?
> Are you using the latest go-mod-upgrade version (v0.4.1) ?

go.mod

```
module github.com/claudiodangelis/qrcp

go 1.14

require (
	github.com/asaskevich/govalidator v0.0.0-20200108200545-475eaeb16496
	github.com/fatih/color v1.9.0 // indirect
	github.com/glendc/go-external-ip v0.0.0-20170425150139-139229dcdddd
	github.com/jhoonb/archivex v0.0.0-20180718040744-0488e4ce1681
	github.com/manifoldco/promptui v0.7.0
	github.com/mattn/go-colorable v0.1.6 // indirect
	github.com/mattn/go-runewidth v0.0.9 // indirect
	github.com/skip2/go-qrcode v0.0.0-20191027152451-9434209cb086
	github.com/spf13/cobra v1.0.0
	gopkg.in/cheggaaa/pb.v1 v1.0.28
)
```

my go version is 1.13
and when I use this program is the latest version at v0.4.1

**Comment by oligot** [comment]
Hi,

We only support the latest 2 Go major versions (currently, this means versions 1.15 and 1.16).
Go modules are a fairly new addition to the language and each new version comes with improvements regarding modules.

![go](https://user-images.githubusercontent.com/1004034/112270420-f1c3bb00-8c79-11eb-815e-d5acea2dadac.png)

Can you update your Go version and try again ?

**Comment by markusressel** [comment]
Had the same issue, upgrading from `1.14` to `1.16.2` fixed it for me :+1:

**Comment by sodul** [comment]
We are using Go 1.16.2 and we do get the exit code. Unfortunately this is a private project and cannot share our go.mod file publicly. I can say that our go.mod is large with over 150 lines.

We tried the latest release and the master branch of go-mod-upgrade.

```
> go-mod-upgrade -v
Discovering modules...
2021/04/01 11:51:54 exit status 1
```

**Comment by oligot** [comment]
I've pushed a commit on master with more descriptive errors

![mod-failed](https://user-images.githubusercontent.com/1004034/113408186-30aaec80-93af-11eb-8e06-a5d7f50013e0.png)

Can you try again and post the result ?

Alternatively, you can run this command (that's the one called by go-mod-upgrade)
> go list -u -mod=mod -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all

And post the result

**Comment by Dentrax** [comment]
Getting same error with:

```bash
$ go-mod-upgrade --verbose
Discovering modules...
2021/04/03 19:02:44 exit status 1

$ go-mod-upgrade --version
go-mod-upgrade version=(undefined) commit=(undefined) date=(undefined)
```

Installed with `go get`:
```bash
$ go get -u github.com/oligot/go-mod-upgrade
go: downloading github.com/oligot/go-mod-upgrade v0.6.0
...
```

**Comment by sodul** [comment]
@oligot here is my output:
```bash
> go version
go version go1.16.3 darwin/amd64

> go install github.com/oligot/go-mod-upgrade@master
go: downloading github.com/oligot/go-mod-upgrade v0.6.1-0.20210402102859-8468540adc62
go: downloading github.com/AlecAivazis/survey/v2 v2.2.9
go: downloading github.com/apex/log v1.9.0
go: downloading github.com/Masterminds/semver/v3 v3.0.3
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: downloading golang.org/x/crypto v0.0.0-20190530122614-20be4c3c3ed5
go: downloading github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037

> ~/go/bin/go-mod-upgrade -p 50
   • Discovering modules...   
   ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: downloading github.com/Azure/go-autorest v1.1.1
go: downloading github.com/Azure/azure-sdk-for-go v0.2.0-beta
go: downloading github.com/Shopify/toxiproxy v1.2.1
go: downloading github.com/coreos/etcd v0.5.0-alpha.5
go: downloading github.com/coreos/go-etcd v0.4.6
go: downloading github.com/dgrijalva/jwt-go v1.0.2
go: downloading github.com/docker/engine v1.13.1
go: downloading github.com/form3tech-oss/jwt-go v1.0.2
go: downloading github.com/pierrec/lz4 v1.0.1
go: downloading github.com/russross/blackfriday v1.6.0
go list -m: loading module retractions for github.com/cactus/go-statsd-client/statsd@v0.0.0-20191106001114-12b4e2b38748: no matching versions for query "latest"
```

**Comment by oligot** [comment]
Hi @Dentrax,

> ```shell
> $ go list -u -mod=mod -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all
> go list -m: loading module retractions for github.com/coreos/go-systemd@v0.0.0-20190321100706-95778dfbb74e: no matching versions for query "latest"
> ```

You should probably use the /v22 suffix for go-systemd, as [shown in their example](https://github.com/coreos/go-systemd/blob/master/examples/activation/activation.go):
```go
import (
	"fmt"
	"os"

	"github.com/coreos/go-systemd/v22/activation"
)
```

After that, you can run
```shell
> go mod tidy
```
which will update the go.mod file accordingly:
```diff
-    github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
+    github.com/coreos/go-systemd/v22 v22.3.1
```

**Comment by oligot** [comment]
Hi @sodul,

> I commented out this line and `go-mod-update` is working, considering it is an indirect dependency that's completely fine, especially since it less us see which modules to update now.
> 
> ```
> github.com/cactus/go-statsd-client/statsd v0.0.0-20191106001114-12b4e2b38748 // indirect
> ```

I'm glad to hear it works for you now !
You could also try to run
```shell
> go mod tidy
```
which should remove unused dependencies

**Comment by Dentrax** [comment]
@oligot Thanks! Maybe we should add a small warning message that tells us to run `$ go mod tidy` command in case if a module does not follow versioning standards.

If `go-mod-upgrade` detect this:
`github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e`
It should print:
`You may need to run 'go mod tidy' in order to correct your version suffixes.`

Wdyt?

**Comment by oligot** [comment]
Unfortunately, this is not so easy as:
- some modules don't have "valid" semantic versions yet: in this case, we should probably open an issue on their side to add proper semantic versioning (and link to the [blog post about publishing go modules](https://blog.golang.org/publishing-go-modules))
- you still have to change the import in your code before running `go mod tidy` (maybe a tool could help here to automatically change the import based on a semantic version like /v22 for a given module)

**Comment by sodul** [comment]
Hi @oligot 

> You could also try to run
> 
> ```shell
> > go mod tidy
> ```
> 
> which should remove unused dependencies

It is an indirect dependency, but still a dependency and `go mod tidy` will not remove that line. We actually run `go mod tidy` as part of our CI pipeline and fail the pipeline if go.mod or go.sum are updated, this allows us to ensure that these files are always consistent and correct and not modified by mistake or a side effect of `go get` that is unrelated to the current project.

The problem here is
```
go list -m: loading module retractions for github.com/cactus/go-statsd-client/statsd@v0.0.0-20191106001114-12b4e2b38748: no matching versions for query "latest"
```
I'm not exactly sure how it got in our go.mod but the latest version for go-statsd-client is 5.0 from January so we'll have to hunt that down. Having an explicit error message is a big help.

**Comment by oligot** [comment]
> Hi @oligot
> 
> > You could also try to run
> > ```shell
> > > go mod tidy
> > ```
> > 
> > 
> > which should remove unused dependencies
> 
> It is an indirect dependency, but still a dependency and `go mod tidy` will not remove that line. We actually run `go mod tidy` as part of our CI pipeline and fail the pipeline if go.mod or go.sum are updated, this allows us to ensure that these files are always consistent and correct and not modified by mistake or a side effect of `go get` that is unrelated to the current project.

Oh, this is a really great idea, I might use this for go-mod-upgrade itself :wink:

> 
> The problem here is
> 
> ```
> go list -m: loading module retractions for github.com/cactus/go-statsd-client/statsd@v0.0.0-20191106001114-12b4e2b38748: no matching versions for query "latest"
> ```
> 
> I'm not exactly sure how it got in our go.mod but the latest version for go-statsd-client is 5.0 from January so we'll have to hunt that down. Having an explicit error message is a big help.

You could try to use [go mod why](https://golang.org/ref/mod#go-mod-why) to see where this dependency comes from:
```bash
> go mod why github.com/cactus/go-statsd-client
```

**Comment by oligot** [comment]
Closing as we now show a more explicit error message when failing to retrieve the module list (see [release v0.6.1](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.6.1)).

Feel free to open another issue if you still have problems.
