### ISSUE TITLE
would it make sense for versioning to be committed 

### ISSUE THREAD

**Issue by gedw99** [oligot/go-mod-upgrade#19]
Maybe i have got this wrong but anyway.

I tend to use go install x.y.z@tag cause it works so well these days, but i dont get version info because its NOT in the golang code that is tagged.

````
go install github.com/oligot/go-mod-upgrade@v0.6.2

which go-mod-upgrade
/Users/apple/workspace/go/bin/go-mod-upgrade

 go-mod-upgrade --version
go-mod-upgrade version=(undefined) commit=(undefined) date=(undefined)

````

The solution is to have a version.go file that always has the correct version.

goreleaser will just overwrite it with the same value during CI i expect ?

What ya think ?

**Comment by gedw99** [comment]
here is an example: https://github.com/alda-lang/alda/blob/master/client/gen/version/main.go

**Comment by oligot** [comment]
Hi,

I just tested it with goreleaser and here is what I get:
```
> go install github.com/goreleaser/goreleaser@v1.1.0
> goreleaser --version
goreleaser version dev
module version: v1.1.0, checksum: h1:YySqqYTX9kxRU0e/fGQrhivXk8/zD4iUOlL7h0I2gBk=

https://goreleaser.com
```

So, this is clearly doable :wink:

**Comment by gedw99** [comment]
nice example !



https://github.com/goreleaser/goreleaser/blob/main/main.go#L29
https://github.com/goreleaser/goreleaser/blob/main/main_test.go#L9

He uses a Task, instead of make file and its here to kick off: 
https://github.com/goreleaser/goreleaser/blob/main/Taskfile.yml#L30

**Comment by oligot** [comment]
This now works in version 0.7.0:
```
> go install github.com/oligot/go-mod-upgrade@v0.7.0
> go-mod-upgrade --version
go-mod-upgrade version dev
module version: v0.7.0
```

**Comment by gedw99** [comment]
thanks @oligot works great for me too.
