### ISSUE TITLE
spinner almost invisible when using light terminal theme

### ISSUE THREAD

**Issue by TheDiveO** [oligot/go-mod-upgrade#23]
The spinner becomes almost invisible when go-mod-upgrade is run in a terminal with a light theme, that is, with a light background color.

**Comment by oligot** [comment]
Hi,
I just opened a PR to set a color (yellow) on the spinner:  #24
Hopefully, this make the spinner more visible.
Could you try on your side and tell me if it's ok ?
Thanks

**Comment by TheDiveO** [comment]
Tried it and it's much clearer to see, it's an almost brownish in a solarized-light theme. Thank you very much!

**Comment by oligot** [comment]
Great ! Released in version [v0.8.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.8.0)

**Comment by TheDiveO** [comment]
One great feature of `go-mod-upgrade` is that it works in the terminal and thus even in VSCode remote sessions with private go module dependencies. I suspect that go modules have been designed to be as much as pain to private repos in order to foster OpenSource! 😀
