### ISSUE TITLE
scanning fails if in workspace mode but not in workspace root directory

### ISSUE THREAD

**Issue by thediveo** [oligot/go-mod-upgrade#28]
Affects github.com/oligot/go-mod-upgrade v0.8.1-0.20220415081324-e8e54c9aa14c

Trying to run `go-mod-upgrade` inside a (Go 1.18) workspace but not from the workspace's root directory but instead from a subdirectory causes `go-mod-upgrade` to fail:

```
   • Workspace mode            gowork=/home/thediveo/ws/foo/go.work
   • Using directory           dir=./bar
   ⨯ upgrade failed            error=chdir ./bar: no such file or directory
```

while in directory `baz`,

```
/home/thediveo/ws/foo/
    bar/
    baz/
```

Might this be due to `go-mod-upgrade` trying to change into a workspace "use" directory from the cwd instead of the root directory of the workspace? Should it rather create an absolute path first based on the workspace root path and a "use"d folder and then cd into that instead of just using the potentially relative use path relative to the cwd? Caveat: use paths might be absolute AFAIK.

**Comment by oligot** [comment]
Hi,
I just pushed a commit on the main branch to fix this issue.
Feel free to reopen this issue if it doesn't work for you.

**Comment by thediveo** [comment]
now works like a charm, thank you very much for quickly fixing it!
