### ISSUE TITLE
go-mod-upgrade not updating workspace projects

### ISSUE THREAD

**Issue by xmlking** [oligot/go-mod-upgrade#33]
to reproduce https://github.com/xmlking/toolkit

**Comment by oligot** [comment]
Hi,

Which version of go-mod-upgrade and go are you using ?
What's the actual problem ?

**Comment by xmlking** [comment]
Latest version v0.9.1.  I tried on two of my workspace repos which have outdated deps, go-mod-upgrade reported no new updates

**Comment by oligot** [comment]
Internally, go-mod-upgrade uses `go list` to fetch the list of dependencies to update:
```bash
go list -m -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' all
```
When run on your project (toolkit), this results in an empty list when there is a go.work file.
The way to "bypass" this is to set the environment variable GOWORK to "off", which does what you want:
```bash
GOWORK="off" go-mod-upgrade
   • Using directory           dir=.../toolkit
? Choose which modules to update  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [ ]  golang.org/x/sync 0.0.0-20220819030929-7fc1605a5dde -> 0.0.0-20220907140024-f12130a52804
```

**Comment by xmlking** [comment]
Thank you @oligot analyzing my issue.
This workaround fix my issue. I will investigate why the list is coming empty

**Comment by oligot** [comment]
Closing this issue following your latest comment.
Feel free to reopen if needed.
