### ISSUE TITLE
searching feature ?

### ISSUE THREAD

**Issue by gedw99** [oligot/go-mod-upgrade#34]
Wondering if someone can help me... Often when working on golang projects i need to find what package is using what package.
Its a "turtles all the way down" thing.

I know this is not related to go-mod-upgrade, but it would be nice to be able to feed in a package and have the software tell me its parents and its children in terms of packages. 

It helps with debugging package craziness.

**Comment by gedw99** [comment]
I ended up “go mod graph “ mixed with grep.

I am thinking about building a pure golang tool to make it easier to search and visualise on top of “ go mod graph” . If your interested let me know

**Comment by oligot** [comment]
Glad you found it !
I'm closing this issue as this is not related to go-mod-upgrade.
