### ISSUE TITLE
not find any module could update in go worksapce

### ISSUE THREAD

**Issue by DingYou** [oligot/go-mod-upgrade#35]
There are two modules in a go workspace like this
<img width="210" alt="image" src="https://user-images.githubusercontent.com/21333087/212841892-008932c1-c68d-4c63-ba16-e5400fafa2cc.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/21333087/212842188-ccdd9449-8c89-4158-a460-c8bc9e3a1c53.png">
 then run go-mod-upgrade,  It always print "All modules are up to date"
<img width="693" alt="image" src="https://user-images.githubusercontent.com/21333087/212842757-2b60b820-f132-4575-a5f0-828fb88bc46e.png">

I tried to find what's wrong. 
When I run `go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all`, I found that the Indirect field is always true. It seems a bug in `go list`.
I think we can change a way to pick out the indirect moudles. 
I forked this repo and tried to use `go mod edit -json` , it works well.
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/21333087/212845780-88df6ed2-2a4b-4701-93bb-c1347c6b51ac.png">

I am going to submit a PR later, please review it, thanks.

**Comment by oligot** [comment]
Hi,

Indeed, this is an issue.
I've solved it a bit differently than your suggestion (in the PR #36).
See commit a5815993e7c285a97510d040d90015e7cde1a436
The main idea is to disable Go workspace mode when running the "go list" command.
I've tested it locally and it now works as expected.

Could you try on your side and tell me if it also works for you ?

Thanks !

**Comment by DingYou** [comment]
> Hi,
> 
> Indeed, this is an issue. I've solved it a bit differently than your suggestion (in the PR #36). See commit [a581599](https://github.com/oligot/go-mod-upgrade/commit/a5815993e7c285a97510d040d90015e7cde1a436) The main idea is to disable Go workspace mode when running the "go list" command. I've tested it locally and it now works as expected.
> 
> Could you try on your side and tell me if it also works for you ?
> 
> Thanks !

Yeah, it works! Simple and useful, what a great solution！Thanks!
