### ISSUE TITLE
Upgrade on server with no gui

### ISSUE THREAD

**Issue by gedw99** [oligot/go-mod-upgrade#38]
Is there a - f flag ?

basically to force it to upgrade everything and not show me the tui  !!

So in CI I can hack the go.mod to that versions of my dependencies 

go mod replace xxx —> yyy 

then do a go mod tidy 
And a go mod-upgrade 
And finally a go mod tidy 
Then build .

this would be so useful for ci where you need to run different versions of client code that’s dependent on server code . 

You can’t always just upgrade client code out in the field so you can flip the switch in CI to use older versions of the client code against the server code and see if your tests break 

Thanks @oligot  for this easy peasy tool. It’s very cool for lazy devs like me :)

**Comment by gedw99** [comment]
My use case is various nats and other systems where they release code without telling you that client version x woks with server version x. 

So you can just find out yourself in CI

**Comment by oligot** [comment]
Hi,

Glad to hear people that find this tool useful :)

Yes, indeeed, we added the -f flag in #11 so you can already use it now.
Maybe we should document all the CLI options/flags in the readme file, so that it’s more discoverable ?

**Comment by gedw99** [comment]
Hey @oligot 

its very useful. 

documenting the option on the cli is definitely needs i think. It's good practice anyway.

**Comment by gedw99** [comment]
@oligot 

its looks like its already there...

``` 
GLOBAL OPTIONS:
   --pagesize value, -p value  Specify page size (default: 10)
   --force, -f                 Force update all modules in non-interactive mode (default: false)
   --verbose, -v               Verbose mode (default: false)
   --hook value                Hook to execute for each updated module
   --help, -h                  show help (default: false)
   --version                   print the version (default: false)
```

so maybe we can close this ?

**Comment by oligot** [comment]
Yeah, I've just included this in the readme.md file so that it's more visible: 25d786cb454211caf0c2681dea38a24c07c63bdd
We can now close this issue.
Thanks for your feedback !
