### ISSUE TITLE
Error: disabled by -mod=readonly

### ISSUE THREAD

**Issue by gedw99** [oligot/go-mod-upgrade#39]
when i run it with no args:

``` 
 ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: updates to go.sum needed, disabled by -mod=readonly
```

have been getting this every since i upgrades go to 1.20.5. Or it might be the repos i am upgrading.. not sure sure right now what going on...

**Comment by gedw99** [comment]
@oligot 

Ok i was right - i changed to go 1.20.4 and then go-mod-upgrade works again.

i guess the go team changed something ...

**Comment by gedw99** [comment]
i have gotip, and so need to try it with that.. maybe its fixed there..

**Comment by lespea** [comment]
https://github.com/golang/go/issues/60667

**Comment by oligot** [comment]
Could you test the [workaround proposed in issue 60667](https://github.com/golang/go/issues/60667#issuecomment-1583462282) and see if it works for you ?

**Comment by gedw99** [comment]
Can sone else try. Am in a work crunch …

**Comment by thediveo** [comment]
Can confirm that it fails for 1.20.5 and works for 1.20.4; and I'm in a crunch too. Looks like this is an upstream issue anyway.

**Comment by gedw99** [comment]
I was planning to try it on gotip today. Curious what it does there.

Will try tomorrow

**Comment by joeblew99** [comment]
i am an idiot . wrong issue 

please see my test here: https://github.com/oligot/go-mod-upgrade/issues/40#issuecomment-1599343190

**Comment by fancar** [comment]
even go list throws  the same:
go list -m -u -f '{{if not .Indirect}}{{.Path}} {{.Deprecated}}{{end}}' all
go: updates to go.sum needed, disabled by -mod=readonly

**Comment by carlmontanari** [comment]
> Could you test the workaround proposed in issue 60667 and see if it works for you ?

confirming saw this issue and that `go mod tidy -compat=1.16` then re-running go-mod-upgrade worked just fine w/ go 1.20.5

**Comment by oligot** [comment]
Thanks @carlmontanari for your feedback !
I'm closing this issue, as this is an upstream bug (https://github.com/golang/go/issues/60667).
Feel free to reopen if the problem persists.
