### ISSUE TITLE
Fails with exit code 1 when go.mod specifies "go 1.14" and dependencies are vendored

### ISSUE THREAD

**Issue by ChrisHines** [oligot/go-mod-upgrade#4]
This problem is due to a change in the `go` command described in the [Go 1.14 release notes](https://golang.org/doc/go1.14#go-command). You must pass the `-mod=mod` option in order for `go list` to consider the `go.mod` file in this scenario.

**Comment by oligot** [comment]
Thanks for the report.
This is now fixed and released in the brand new version [0.2.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.2.0).
