### ISSUE TITLE
unknown directive: toolchain

### ISSUE THREAD

**Issue by guikcd** [oligot/go-mod-upgrade#47]
go-mod-upgrade currently fail to run if `toolchain` keyword is used:

```
$ go-mod-upgrade 
   • Using directory           dir=.
   ⨯ upgrade failed            error=Error running go command to discover modules: exit status 1 stderr=go: errors parsing go.mod:
go.mod:5: unknown directive: toolchain
```

I'm trying to upgrade some of modules in https://github.com/vmware-tanzu/velero/blob/main/go.mod, but I guess it's reproducible with any go.mod file which include [toolchain](https://go.dev/doc/modules/gomod-ref#toolchain). Temporary removing the toolchain keyword temporary fix the issue.

**Comment by guikcd** [comment]
I'm sorry, this is probably not an issue with go-mod-upgrade itself:

```
$ go get -u github.com/aws/aws-sdk-go-v2
go: errors parsing go.mod:
go.mod:5: unknown directive: toolchain
```

**Comment by guikcd** [comment]
This is not an issue, sorry for the noise.

**Comment by oligot** [comment]
No problem, glad that you found a solution to your problem.
