### ISSUE TITLE
`replace` directives support

### ISSUE THREAD

**Issue by novadev94** [oligot/go-mod-upgrade#55]
Currently `go-mod-upgrade` doesn't work with `replace` directives (e.g, https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/)

Instead of following the relative paths or ignore them, it just raises an error

```
   ⨯ upgrade failed            
error=Error running go command to discover modules: exit status 1 stderr=
go: unrecognized import path "github.com/myorg/mypkg": reading  https://github.com/myorg/mypkg?go-get=1 404 Not Found
```

**Comment by oligot** [comment]
go-mod-upgrade supports Go workspace since [v0.9.0](https://github.com/oligot/go-mod-upgrade/releases/tag/v0.9.0), which is the « new » way when working with multiples modules.
More info in [Get familiar with workspaces](https://go.dev/blog/get-familiar-with-workspaces)

**Comment by novadev94** [comment]
From my personal experience, I think using Go workspace (`go.work`) and `replace` directives for local development aren't mutually exclusive - as seen in the long discussion here https://github.com/golang/go/issues/54264. So with all the mentioned hassles, we still had to use `replace` directives in `go.mod` files.

However, I do agree that this use case might be uncommon to be supported by `go-mod-upgrade`.

**Comment by oligot** [comment]
Yeah, this kind of use case Is unfortunately not supported in go-mod-upgrade…
